apiVersion: appclacks.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: appclacks-creds
      namespace: crossplane-system
      key: credentials
