/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DNSObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type DNSParameters struct {

	// (String) Health check description
	// Health check description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Domain to check
	// Domain to check
	// +kubebuilder:validation:Required
	Domain *string `json:"domain" tf:"domain,omitempty"`

	// (Boolean) Enable the health check on the Appclacks platform
	// Enable the health check on the Appclacks platform
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Set of String) Expected IP addresses in the answer
	// Expected IP addresses in the answer
	// +kubebuilder:validation:Optional
	ExpectedIps []*string `json:"expectedIps,omitempty" tf:"expected_ips,omitempty"`

	// (String) Health check interval (example: 30s)
	// Health check interval (example: 30s)
	// +kubebuilder:validation:Optional
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`

	// (Map of String) Health check labels
	// Health check labels
	// +kubebuilder:validation:Optional
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Health check name
	// Health check name
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// (String) Health check timeout (example: 5s)
	// Health check timeout (example: 5s)
	// +kubebuilder:validation:Optional
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

// DNSSpec defines the desired state of DNS
type DNSSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DNSParameters `json:"forProvider"`
}

// DNSStatus defines the observed state of DNS.
type DNSStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DNSObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// DNS is the Schema for the DNSs API. Execute a DNS query and optionally verify the request answer
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,appclacks}
type DNS struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DNSSpec   `json:"spec"`
	Status            DNSStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DNSList contains a list of DNSs
type DNSList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DNS `json:"items"`
}

// Repository type metadata.
var (
	DNS_Kind             = "DNS"
	DNS_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DNS_Kind}.String()
	DNS_KindAPIVersion   = DNS_Kind + "." + CRDGroupVersion.String()
	DNS_GroupVersionKind = CRDGroupVersion.WithKind(DNS_Kind)
)

func init() {
	SchemeBuilder.Register(&DNS{}, &DNSList{})
}
