/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type TCPObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TCPParameters struct {

	// (String) Health check description
	// Health check description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Enable the health check on the Appclacks platform
	// Enable the health check on the Appclacks platform
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Health check interval (example: 30s)
	// Health check interval (example: 30s)
	// +kubebuilder:validation:Optional
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`

	// (Map of String) Health check labels
	// Health check labels
	// +kubebuilder:validation:Optional
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Health check name
	// Health check name
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// (Number) Health check port
	// Health check port
	// +kubebuilder:validation:Required
	Port *float64 `json:"port" tf:"port,omitempty"`

	// (Boolean) If set to true, the health check will be considered successful if the TCP connection fails
	// If set to true, the health check will be considered successful if the TCP connection fails
	// +kubebuilder:validation:Optional
	ShouldFail *bool `json:"shouldFail,omitempty" tf:"should_fail,omitempty"`

	// (String) Health check target (can be a domain or an IP address)
	// Health check target (can be a domain or an IP address)
	// +kubebuilder:validation:Required
	Target *string `json:"target" tf:"target,omitempty"`

	// (String) Health check timeout (example: 5s)
	// Health check timeout (example: 5s)
	// +kubebuilder:validation:Optional
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

// TCPSpec defines the desired state of TCP
type TCPSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TCPParameters `json:"forProvider"`
}

// TCPStatus defines the observed state of TCP.
type TCPStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TCPObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// TCP is the Schema for the TCPs API. Create a TCP connection on the target
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,appclacks}
type TCP struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TCPSpec   `json:"spec"`
	Status            TCPStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TCPList contains a list of TCPs
type TCPList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TCP `json:"items"`
}

// Repository type metadata.
var (
	TCP_Kind             = "TCP"
	TCP_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TCP_Kind}.String()
	TCP_KindAPIVersion   = TCP_Kind + "." + CRDGroupVersion.String()
	TCP_GroupVersionKind = CRDGroupVersion.WithKind(TCP_Kind)
)

func init() {
	SchemeBuilder.Register(&TCP{}, &TCPList{})
}
